'*****************************************************
' Script Name: HelloWorld.vbs
'     Purpose: Demonstrate difference between Cscript.exe and Wscript.exe.
'              Cscript echoes to CMD.EXE window, while Wscript will
'              pop up a graphical dialog box.
'       Notes: MsgBox("Hello World!") will always appear in a GUI box.
'              The "SIG" stuff at the bottom is a WSH 5.6 digital signature.
'*****************************************************



WScript.Echo "Hello World!"



'END OF SCRIPT ***************************************


'' SIG '' Begin signature block
'' SIG '' MIIRYAYJKoZIhvcNAQcCoIIRUTCCEU0CAQExDjAMBggq
'' SIG '' hkiG9w0CBQUAMGYGCisGAQQBgjcCAQSgWDBWMDIGCisG
'' SIG '' AQQBgjcCAR4wJAIBAQQQTvApFpkntU2P5azhDxfrqwIB
'' SIG '' AAIBAAIBAAIBAAIBADAgMAwGCCqGSIb3DQIFBQAEEOzx
'' SIG '' 5CE6x1YqdZm6YLovaeaggg8OMIIGsDCCBZigAwIBAgIK
'' SIG '' FfRkngAAAAAAKjANBgkqhkiG9w0BAQQFADCBlTEcMBoG
'' SIG '' CSqGSIb3DQEJARYNc2Fuc0BzYW5zLm9yZzELMAkGA1UE
'' SIG '' BhMCVVMxCzAJBgNVBAgTAlR4MQ8wDQYDVQQHEwZEYWxs
'' SIG '' YXMxFzAVBgNVBAoTDlNBTlMgSW5zdGl0dXRlMTEwLwYD
'' SIG '' VQQDEyhTQU5TLUluc3RpdHV0ZS1FbnRlcnByaXNlLVN1
'' SIG '' Ym9yZGluYXRlLUNBMB4XDTAzMDMyMDIwMjkyMloXDTAz
'' SIG '' MTAwMTIwMjQ1MlowEDEOMAwGA1UEAxMFSmFzb24wgZ8w
'' SIG '' DQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOTSY0HdvXXw
'' SIG '' Y2CvRBMtooOcyvDbcGd3JA+pyWk0Uae9AmFznz0Mvx6w
'' SIG '' bPc2Vm9qQ32cDCasLX6+a73oH8jXihDobw5Jvn97gVvV
'' SIG '' /eVKtSilOsPlrb6rXwVGTgZB06FjWeLFcuqBmNfvuUFS
'' SIG '' CUJYS5Y82K/R3G3hSInQ1Tt3jk5RAgMBAAGjggQIMIIE
'' SIG '' BDALBgNVHQ8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUH
'' SIG '' AwMwJQYJKwYBBAGCNxQCBBgeFgBDAG8AZABlAFMAaQBn
'' SIG '' AG4AaQBuAGcwHQYDVR0OBBYEFJSy4/4E4jGf4JU5uZLI
'' SIG '' ZDqNkuq2MIHFBgNVHSMEgb0wgbqAFOol9uD3/SLIseAw
'' SIG '' TDpJ7osZ6HskoYGVpIGSMIGPMRwwGgYJKoZIhvcNAQkB
'' SIG '' Fg1zYW5zQHNhbnMub3JnMQswCQYDVQQGEwJVUzELMAkG
'' SIG '' A1UECBMCVHgxDzANBgNVBAcTBkRhbGxhczEXMBUGA1UE
'' SIG '' ChMOU0FOUyBJbnN0aXR1dGUxKzApBgNVBAMTIlNBTlMt
'' SIG '' SW5zdGl0dXRlLVN0YW5kLUFsb25lLVJvb3QtQ0GCCmHA
'' SIG '' 5fsAAAAAAAIwggFHBgNVHR8EggE+MIIBOjCB3KCB2aCB
'' SIG '' 1oaB02xkYXA6Ly8vQ049U0FOUy1JbnN0aXR1dGUtRW50
'' SIG '' ZXJwcmlzZS1TdWJvcmRpbmF0ZS1DQSxDTj1tZWdhbG9u
'' SIG '' LENOPUNEUCxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNl
'' SIG '' cyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERD
'' SIG '' PXVzYSxEQz1zYW5zLERDPW9yZz9jZXJ0aWZpY2F0ZVJl
'' SIG '' dm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Y2xhc3M9Y1JM
'' SIG '' RGlzdHJpYnV0aW9uUG9pbnQwWaBXoFWGU2h0dHA6Ly9t
'' SIG '' ZWdhbG9uLnVzYS5zYW5zLm9yZy9DZXJ0RW5yb2xsL1NB
'' SIG '' TlMtSW5zdGl0dXRlLUVudGVycHJpc2UtU3Vib3JkaW5h
'' SIG '' dGUtQ0EuY3JsMIIBVgYIKwYBBQUHAQEEggFIMIIBRDCB
'' SIG '' ywYIKwYBBQUHMAKGgb5sZGFwOi8vL0NOPVNBTlMtSW5z
'' SIG '' dGl0dXRlLUVudGVycHJpc2UtU3Vib3JkaW5hdGUtQ0Es
'' SIG '' Q049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2Vz
'' SIG '' LENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9
'' SIG '' dXNhLERDPXNhbnMsREM9b3JnP2NBQ2VydGlmaWNhdGU/
'' SIG '' YmFzZT9vYmplY3RjbGFzcz1jZXJ0aWZpY2F0aW9uQXV0
'' SIG '' aG9yaXR5MHQGCCsGAQUFBzAChmhodHRwOi8vbWVnYWxv
'' SIG '' bi51c2Euc2Fucy5vcmcvQ2VydEVucm9sbC9tZWdhbG9u
'' SIG '' LnVzYS5zYW5zLm9yZ19TQU5TLUluc3RpdHV0ZS1FbnRl
'' SIG '' cnByaXNlLVN1Ym9yZGluYXRlLUNBLmNydDAtBgNVHREE
'' SIG '' JjAkoCIGCisGAQQBgjcUAgOgFAwSamFzb25AdXNhLnNh
'' SIG '' bnMub3JnMA0GCSqGSIb3DQEBBAUAA4IBAQACxmB8YF4a
'' SIG '' fbFlinyNH4Cxnlb6ZC1fYUecMfD4V4BDauuyr1Ai1Mcg
'' SIG '' I6huufEKwzaiKfjOispDbjax24JzOC7Kzab+GNqd/zH5
'' SIG '' 4L6+8ZLbBEvov6J4QVR86N97HxihXRfp1QZHV0K0CLIS
'' SIG '' nVzKkoip+bydznWQQhjidnEuHKJUCJF/+cA7vW36i3Cw
'' SIG '' wBfyDSllJ7+z936LmuiMoMNM2LB9dAaGHw4IdTiKVQD9
'' SIG '' HmSx08Kum+CYdbEsqnVBbOxAUq5OhQWT7INa1/QoTGSq
'' SIG '' SK687Ko1mP5U2R4j17CrEV96ONqncgSbFJ33UU4qC/uH
'' SIG '' HsJiusjiCNQTge53EplqDBIRMIIIVjCCBj6gAwIBAgIK
'' SIG '' YcDl+wAAAAAAAjANBgkqhkiG9w0BAQQFADCBjzEcMBoG
'' SIG '' CSqGSIb3DQEJARYNc2Fuc0BzYW5zLm9yZzELMAkGA1UE
'' SIG '' BhMCVVMxCzAJBgNVBAgTAlR4MQ8wDQYDVQQHEwZEYWxs
'' SIG '' YXMxFzAVBgNVBAoTDlNBTlMgSW5zdGl0dXRlMSswKQYD
'' SIG '' VQQDEyJTQU5TLUluc3RpdHV0ZS1TdGFuZC1BbG9uZS1S
'' SIG '' b290LUNBMB4XDTAyMTAwMTIwMTQ1MloXDTAzMTAwMTIw
'' SIG '' MjQ1MlowgZUxHDAaBgkqhkiG9w0BCQEWDXNhbnNAc2Fu
'' SIG '' cy5vcmcxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJUeDEP
'' SIG '' MA0GA1UEBxMGRGFsbGFzMRcwFQYDVQQKEw5TQU5TIElu
'' SIG '' c3RpdHV0ZTExMC8GA1UEAxMoU0FOUy1JbnN0aXR1dGUt
'' SIG '' RW50ZXJwcmlzZS1TdWJvcmRpbmF0ZS1DQTCCASIwDQYJ
'' SIG '' KoZIhvcNAQEBBQADggEPADCCAQoCggEBALjQUiConCxv
'' SIG '' B6ulwwo7gwVLPWO1MhqrBb5X+kqTnJ9oABMACEB0LpcU
'' SIG '' WPq/sb9O6IjLbAKtuCPDYUgKwjOVuYZX0oDVfXTyKXng
'' SIG '' /es9lDp2unno0l0hAWREWm8gTCs8TyIoZeTWJfDJ9vn6
'' SIG '' FB28j1ITE80hwecEXbAk9esikUET4RGuZT1t8TvbV3Rl
'' SIG '' wfU4Ej9GRL96jxQYdIOl6+QEpTCoIAEkfmQ36PWG/otA
'' SIG '' EPpNpBozsngig84kYgzTCmmRz7e7buF3FhuVrGzgs/wM
'' SIG '' A3vV32+E6yKdZKu4IX16FAZPLRftUsrrI9Zm/ag00hQz
'' SIG '' D9l2tYM7tRbfApWcM8pNEgMCAwEAAaOCA6owggOmMBAG
'' SIG '' CSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBTqJfbg9/0i
'' SIG '' yLHgMEw6Se6LGeh7JDALBgNVHQ8EBAMCAcYwDwYDVR0T
'' SIG '' AQH/BAUwAwEB/zCBywYDVR0jBIHDMIHAgBTzRaErsMaa
'' SIG '' CwKo5tEVPinyOfDMj6GBlaSBkjCBjzEcMBoGCSqGSIb3
'' SIG '' DQEJARYNc2Fuc0BzYW5zLm9yZzELMAkGA1UEBhMCVVMx
'' SIG '' CzAJBgNVBAgTAlR4MQ8wDQYDVQQHEwZEYWxsYXMxFzAV
'' SIG '' BgNVBAoTDlNBTlMgSW5zdGl0dXRlMSswKQYDVQQDEyJT
'' SIG '' QU5TLUluc3RpdHV0ZS1TdGFuZC1BbG9uZS1Sb290LUNB
'' SIG '' ghA4RUu/TQASgUrKHf5CBRb4MIIBOQYDVR0fBIIBMDCC
'' SIG '' ASwwgdWggdKggc+GgcxsZGFwOi8vL0NOPVNBTlMtSW5z
'' SIG '' dGl0dXRlLVN0YW5kLUFsb25lLVJvb3QtQ0EsQ049bW90
'' SIG '' aHJhLENOPUNEUCxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2
'' SIG '' aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9u
'' SIG '' LERDPXVzYSxEQz1zYW5zLERDPW9yZz9jZXJ0aWZpY2F0
'' SIG '' ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Y2xhc3M9
'' SIG '' Y1JMRGlzdHJpYnV0aW9uUG9pbnQwUqBQoE6GTGh0dHA6
'' SIG '' Ly9tb3RocmEudXNhLnNhbnMub3JnL0NlcnRFbnJvbGwv
'' SIG '' U0FOUy1JbnN0aXR1dGUtU3RhbmQtQWxvbmUtUm9vdC1D
'' SIG '' QS5jcmwwggFIBggrBgEFBQcBAQSCATowggE2MIHFBggr
'' SIG '' BgEFBQcwAoaBuGxkYXA6Ly8vQ049U0FOUy1JbnN0aXR1
'' SIG '' dGUtU3RhbmQtQWxvbmUtUm9vdC1DQSxDTj1BSUEsQ049
'' SIG '' UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2Vydmlj
'' SIG '' ZXMsQ049Q29uZmlndXJhdGlvbixEQz11c2EsREM9c2Fu
'' SIG '' cyxEQz1vcmc/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVj
'' SIG '' dGNsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkwbAYI
'' SIG '' KwYBBQUHMAKGYGh0dHA6Ly9tb3RocmEudXNhLnNhbnMu
'' SIG '' b3JnL0NlcnRFbnJvbGwvbW90aHJhLnVzYS5zYW5zLm9y
'' SIG '' Z19TQU5TLUluc3RpdHV0ZS1TdGFuZC1BbG9uZS1Sb290
'' SIG '' LUNBLmNydDANBgkqhkiG9w0BAQQFAAOCAgEARlHvSdsk
'' SIG '' VV7HNCphs90pMjtK49PR0sLy5YWEXHrqXyO5SmAUidRY
'' SIG '' maljd07jxqObNoIJnx32gAVCBJZO/9gWzNTbE62mOpSD
'' SIG '' FQbDfu2HVLZqYvj+xDJnypuq2UGH1qeSCPyWMSI35XMr
'' SIG '' UzsSE79lsNO1vLjscgQlD4J8K0d53ph88/eElef7MDtY
'' SIG '' 5hTI50M4i0QdQVBJVFiR/hSBnrU489WfXCoRgSzOojbO
'' SIG '' Fs2qPMpFcbxPCrkW4eVDQeS7OCSnGEotvWjsGzxFJFwl
'' SIG '' kt9YjrENaY26rigBGSC4wP6qWWnI3+s7tqVZ/hfowLov
'' SIG '' YH+EnG9YPL6MRiyzlmtCtLT1E10iNlYn5tCS6WWdeYqB
'' SIG '' fa+wJ5gUBfWYJWU6cfqyn6eyJnBjTvEO+KAjR4cR+QIL
'' SIG '' SXkmNz/FDXraOlUHVbG7CKrqW+V9gYM8e4seMr3wmf1B
'' SIG '' iZ0NZhQltjucPC/tJniQVwl50cfsjB8tCCbmTZNJvPV2
'' SIG '' V4fwgLIs+kjw15RAwWa8qSu2xJlRtWviW0o4WPxWuIzy
'' SIG '' WIV4Ruxi77HlYsS7k87wJwdO7YuJfKs0Kh18DhCKJbMR
'' SIG '' wOMZGXZorv6m2wGukeCM4nnJi0bEQgin/cN1xqkdBYHe
'' SIG '' dxEodPijCOSkuC8lv66utIUZp68Qbt3WcnhL8qQo9oub
'' SIG '' Y4HwuTnaSfyX0hAxggG8MIIBuAIBATCBpDCBlTEcMBoG
'' SIG '' CSqGSIb3DQEJARYNc2Fuc0BzYW5zLm9yZzELMAkGA1UE
'' SIG '' BhMCVVMxCzAJBgNVBAgTAlR4MQ8wDQYDVQQHEwZEYWxs
'' SIG '' YXMxFzAVBgNVBAoTDlNBTlMgSW5zdGl0dXRlMTEwLwYD
'' SIG '' VQQDEyhTQU5TLUluc3RpdHV0ZS1FbnRlcnByaXNlLVN1
'' SIG '' Ym9yZGluYXRlLUNBAgoV9GSeAAAAAAAqMAwGCCqGSIb3
'' SIG '' DQIFBQCgbDAQBgorBgEEAYI3AgEMMQIwADAZBgkqhkiG
'' SIG '' 9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgEL
'' SIG '' MQ4wDAYKKwYBBAGCNwIBFTAfBgkqhkiG9w0BCQQxEgQQ
'' SIG '' T/9SilMFHKR7k60nfd2U3jANBgkqhkiG9w0BAQEFAASB
'' SIG '' gIMbqjNF6JxR+ePo8Aji0nZSqp782UrCuvFEViccTvHh
'' SIG '' jxYBvZB9kDd052w3X4W57nj5Vh4FIB8SH+LihcQE4vOx
'' SIG '' WetX3ve7c3pn3Fa6W+nW9HpJyraAiXQAu23w/wgJXGfa
'' SIG '' c84axhCuh1jj2kBfTsJUW4laNmaQZY9xvTxC7AUU
'' SIG '' End signature block
