'*****************************************************
' Script Name: NeoGUI.vbs
'     Purpose: fool around...practical jokes...
'*****************************************************

Set oWshShell = WScript.CreateObject("WScript.Shell")
oWshShell.Run("notepad.exe")
WScript.Sleep(100)
oWshShell.AppActivate("Untitled")
oWshShell.SendKeys("{ENTER}")
oWshShell.SendKeys("{ENTER}")
oWshShell.SendKeys("{ENTER}")
WScript.Sleep(800)
oWshShell.SendKeys(" H")
WScript.Sleep(200)
oWshShell.SendKeys("e")
WScript.Sleep(500)
oWshShell.SendKeys("l")
WScript.Sleep(200)
oWshShell.SendKeys("l")
WScript.Sleep(300)
oWshShell.SendKeys("o ")
WScript.Sleep(600)

oWshShell.SendKeys("n")
WScript.Sleep(400)
oWshShell.SendKeys("{BACKSPACE}")
WScript.Sleep(300)
oWshShell.SendKeys("N")
WScript.Sleep(500)
oWshShell.SendKeys("e")
WScript.Sleep(400)
oWshShell.SendKeys("o.")
WScript.Sleep(700)

oWshShell.SendKeys("{ENTER}")
oWshShell.SendKeys("{ENTER}")

oWshShell.SendKeys(" I ")
WScript.Sleep(200)
oWshShell.SendKeys("k")
WScript.Sleep(300)
oWshShell.SendKeys("n")
WScript.Sleep(400)
oWshShell.SendKeys("o")
WScript.Sleep(200)
oWshShell.SendKeys("w ")
WScript.Sleep(200)
oWshShell.SendKeys("w")
WScript.Sleep(200)
oWshShell.SendKeys("h")
WScript.Sleep(200)
oWshShell.SendKeys("a")
WScript.Sleep(400)
oWshShell.SendKeys("a")
WScript.Sleep(600)
oWshShell.SendKeys("{BACKSPACE}")
WScript.Sleep(200)
oWshShell.SendKeys("t")
WScript.Sleep(400)
oWshShell.SendKeys(" y")
WScript.Sleep(200)
oWshShell.SendKeys("o")
WScript.Sleep(100)
oWshShell.SendKeys("u")
WScript.Sleep(400)
oWshShell.SendKeys("'")
WScript.Sleep(200)
oWshShell.SendKeys("r")
WScript.Sleep(100)
oWshShell.SendKeys("e ")
WScript.Sleep(200)
oWshShell.SendKeys("l")
WScript.Sleep(200)
oWshShell.SendKeys("o")
WScript.Sleep(300)
oWshShell.SendKeys("o")
WScript.Sleep(100)
oWshShell.SendKeys("k")
WScript.Sleep(200)
oWshShell.SendKeys("i")
WScript.Sleep(200)
oWshShell.SendKeys("n")
WScript.Sleep(100)
oWshShell.SendKeys("g")
WScript.Sleep(300)
oWshShell.SendKeys(" f")
WScript.Sleep(300)
oWshShell.SendKeys("o")
WScript.Sleep(200)
oWshShell.SendKeys("r")
WScript.Sleep(100)
oWshShell.SendKeys(".")
WScript.Sleep(400)
oWshShell.SendKeys(".")
WScript.Sleep(500)
oWshShell.SendKeys(".")
WScript.Sleep(100)
oWshShell.SendKeys("{ENTER}")
WScript.Sleep(200)
oWshShell.SendKeys("{ENTER}")
WScript.Sleep(300)
oWshShell.SendKeys("{ENTER}")
WScript.Sleep(400)
oWshShell.SendKeys("{ENTER}")
WScript.Sleep(800)
oWshShell.SendKeys("{ENTER}")
WScript.Sleep(5000)
oWshShell.SendKeys("%{F4}")
oWshShell.SendKeys("%n")


'END OF SCRIPT ***************************************

