########################################################################
#.NOTES
#   This is just an example of a digitally-signed PowerShell script.
#   As you can see, the executable code is not encrypted, only signed.
########################################################################

Get-Process
Get-Service
Get-Alias


# SIG # Begin signature block
# MIIJVAYJKoZIhvcNAQcCoIIJRTCCCUECAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUWVkEKHwc7qGR+hSPi5nVMrg5
# 0NegggbBMIIGvTCCBKWgAwIBAgITPQAAAAy87QHfu5v9DgAAAAAADDANBgkqhkiG
# 9w0BAQsFADBFMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxFzAVBgoJkiaJk/IsZAEZ
# Fgd0ZXN0aW5nMRMwEQYDVQQDEwpUZXN0aW5nLUNBMB4XDTIwMDEwMzEyMDUzNVoX
# DTIxMDEwMjEyMDUzNVowWDEVMBMGCgmSJomT8ixkARkWBWxvY2FsMRcwFQYKCZIm
# iZPyLGQBGRYHdGVzdGluZzEOMAwGA1UEAxMFVXNlcnMxFjAUBgNVBAMTDUFkbWlu
# aXN0cmF0b3IwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDBhn1MXao0
# Lks8Tjvdkf4BxbAVFr0kdUyZC+sfu5Ydpjn2V4ny3jLN12VupV93gef9PlmIqWb5
# M6s5fuwRs1AotIOvzbhwkpVgHyscqNfUe/IJEAUIMGJ35MOx/clXBkYxN79HEqDS
# yujM/fnPuoZAPFL+CSxYA1tDSo7w/qiTLdw54rGo4/qYfUjdH+du/p9hYwTKJtV5
# OQE1D5ajlJZDkEFfeKTv0JjAISCzMqxUwr2tJmQS3RKjcXc5RoU0QLgRKsTi/dpp
# THnqRdudlnENRpuISgSZz1zrVqF//7lfxBkRd81FhyFDpeipTH2w1BuPRF9gDgtn
# K4qOAsdy5C/hAgMBAAGjggKRMIICjTA7BgkrBgEEAYI3FQcELjAsBiQrBgEEAYI3
# FQiBhbh2gd7EZ4XZmwSDltpYhrzdcAuV4UOUv0sCAWQCAQIwEwYDVR0lBAwwCgYI
# KwYBBQUHAwMwDgYDVR0PAQH/BAQDAgeAMBsGCSsGAQQBgjcVCgQOMAwwCgYIKwYB
# BQUHAwMwHQYDVR0OBBYEFPXaqd6tEuGvLseOpnEvkj6uNKrmMB8GA1UdIwQYMBaA
# FMoLytM3Xr/VQaS+M39fN9MRyCRJMIHSBgNVHR8EgcowgccwgcSggcGggb6Ggbts
# ZGFwOi8vL0NOPVRlc3RpbmctQ0EsQ049V0lOLUY4QU5VTUhWSkg1LENOPUNEUCxD
# Tj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1
# cmF0aW9uLERDPXRlc3RpbmcsREM9bG9jYWw/Y2VydGlmaWNhdGVSZXZvY2F0aW9u
# TGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERpc3RyaWJ1dGlvblBvaW50MIG+Bggr
# BgEFBQcBAQSBsTCBrjCBqwYIKwYBBQUHMAKGgZ5sZGFwOi8vL0NOPVRlc3Rpbmct
# Q0EsQ049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2Vz
# LENOPUNvbmZpZ3VyYXRpb24sREM9dGVzdGluZyxEQz1sb2NhbD9jQUNlcnRpZmlj
# YXRlP2Jhc2U/b2JqZWN0Q2xhc3M9Y2VydGlmaWNhdGlvbkF1dGhvcml0eTA2BgNV
# HREELzAtoCsGCisGAQQBgjcUAgOgHQwbQWRtaW5pc3RyYXRvckB0ZXN0aW5nLmxv
# Y2FsMA0GCSqGSIb3DQEBCwUAA4ICAQCth+H031TKw0UJFXzddAI+o5txY4Q29EgW
# nbbwiVCGe8UU4M8lICxbHJ500PKESX2YNVEci6o4l5jev00hCNuEYStdUTlyMxNi
# 8umdMlHWOIamMW8aMuOEUzwyig/7W4GoSKIqJ/cgDi/nk0aS0Rf76suj+1MPnLk1
# c6g3rAYJuTWL9UvOAoq3RgURTGbyFqJ/sXARZ54RQ4xLxdbeTJRre7XCCG82sk+P
# Gf7yN678xoyZ4KAIJLl30SVcEhgfGBV9DzhF/+6miCdS4iD1RVTmzST5E9tTQ88b
# Y2+L8P0a6slgO+fn1/eqdEho5Yl9JITcz8p6eIsbu05nkkk5P96YOmTr76oyGeVc
# Nm3sB5tlT6uNZas2N12+gl5fvTaSqCgajYkJFy8k6ZTyyxiHdwkjWUmXlrW66quH
# F2MJKzkJdt0/bgWSpjRtxHuHD96c05ZG4y0Ty0Yqxs3FcsCOPuiY+FkBzxysNGrr
# ZMG0Ftagcsg7RC5BDY9IgqiQyasfMCUlgANUdMbpwfZFuV3LxKPHlqZ3VBorp/+U
# p8T7IvikX8Um1MceCxujJf44nrdConANBNx+jU2FDkxF9iDe+1X6pqBp0C14Fb+m
# aMVvhqmkN18VyhZuzpyJPSUmjlj3094BEByDE70xgG1C+lBZDVetvvQIEOuJdxfB
# CTNn9aBSPDGCAf0wggH5AgEBMFwwRTEVMBMGCgmSJomT8ixkARkWBWxvY2FsMRcw
# FQYKCZImiZPyLGQBGRYHdGVzdGluZzETMBEGA1UEAxMKVGVzdGluZy1DQQITPQAA
# AAy87QHfu5v9DgAAAAAADDAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAig
# AoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgEL
# MQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQU/WcS86GBBRvEq35t01DV
# GVccCvIwDQYJKoZIhvcNAQEBBQAEggEAWyUkZDvCb/x7U/3z2YIQFsRjr6pQAYE5
# pds8PRcb6hPqkBrOsOvVOkTsmR8OFb/uo8JrxCiPMzdF8CU+lkAT58GDzzQYgb2F
# Z41C/mnAQ3M98RcMZJRghmwdktJLaN6rWzYE5wZo6tKO9jidWYMFoeoEV9tL+egC
# nJ3tjIshNxnDWBfE/B3dMEIQ5BsZqbhN+Rsijh5fQeytnryx8gMrmStFdkzXCzdQ
# NESpbUNPAPYMuvxCVCzSxTo16ey45EKSDnISONy0wl2WG1Gyb3mpj6mh+Hx+fghC
# axItQ8PzUpeJ1wx1v73NbtlBfLoyRiqZX4L5yTAttrw5BbtjyKPOkQ==
# SIG # End signature block
